### PR TITLE
Add argument handler class

### PR DESCRIPTION
**Pull request by ch-evergen**
## What?

Move argument handling and config setup out of main.py into its own class.

## Why?

This makes argument handling and config creation testable and included in coverage checks.

## Testing/Proof

Automated testing

### CODE REVIEW

**Review by serroba — APPROVED** [review]
😍 great! 
Great simplification :)

**Comment by serroba** [comment]
oh, is this still a WIP? I approved it, but I just noticed you may want to keep working on this

**Comment by ch-evergen** [comment]
> oh, is this still a WIP? I approved it, but I just noticed you may want to keep working on this

Happy to go ahead with this as is, but I made it WIP for now in case we want to make more changes to main.py as discussed in #41

**Comment by serroba** [comment]
I rather cohesive units of change. This is good as is now. If you want to do further improvements, let's open new PRS instead

**Pull request merged**
